use std::collections::{HashMap, VecDeque};
use std::sync::Arc;
use tokio::sync::{broadcast, mpsc, Mutex, RwLock};

use crate::alert::{AlertEvent, AlertTracker};
use crate::asr::AsrClient;
use crate::config::Config;
use crate::llm::LlmClient;
use crate::monitor::MonitorProfile;
use crate::telegram::TelegramNotifier;
use crate::vlm::VlmClient;

/// Maximum number of summary entries to retain.
pub const MAX_SUMMARIES: usize = 20;

/// A single inference result from analyzing a camera frame.
#[derive(Debug, Clone, serde::Serialize)]
pub struct FrameResult {
    pub camera_id: String,
    pub frame_no: u64,
    pub time: String,
    pub infer_secs: f64,
    pub model: String,
    pub text: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub parsed_json: Option<serde_json::Value>,
}

/// A periodic activity summary generated by the summary scheduler.
/// Persisted in `AppState.summaries` so the dashboard can show recent
/// summaries to new visitors.
#[derive(Debug, Clone, serde::Serialize)]
pub struct SummaryEntry {
    /// Local time when the summary was generated, formatted "YYYY-MM-DD HH:MM".
    pub time: String,
    pub window_min: u32,
    pub text: String,
}

/// Tagged envelope for SSE events. Internally tagged so consumers can
/// branch on the `kind` field without nested wrapping.
#[derive(Debug, Clone, serde::Serialize)]
#[serde(tag = "kind", rename_all = "lowercase")]
pub enum SseEvent {
    Result(FrameResult),
    Summary(SummaryEntry),
}

/// Per-camera state tracked by the server.
pub struct CameraState {
    pub camera_id: String,
    pub name: String,
    pub frame_no: u64,
    /// Most recent JPEG frame bytes (for snapshot / web UI preview).
    pub latest_frame: Option<Vec<u8>>,
    /// Rolling buffer of recent results (newest last).
    pub results: Vec<FrameResult>,
    pub running: bool,
    /// Channel for sending commands to this camera via WebSocket.
    pub cmd_tx: Option<mpsc::UnboundedSender<String>>,
    /// Capabilities reported by the camera on registration (e.g. "ptz", "patrol").
    pub capabilities: Vec<String>,
}

impl CameraState {
    pub fn new(camera_id: String, name: String) -> Self {
        Self {
            camera_id,
            name,
            frame_no: 0,
            latest_frame: None,
            results: Vec::new(),
            running: false,
            cmd_tx: None,
            capabilities: Vec::new(),
        }
    }

    /// Check if this camera supports a given capability.
    pub fn has_capability(&self, cap: &str) -> bool {
        self.capabilities.iter().any(|c| c == cap)
    }

    /// Build a chronological digest (oldest first) of the last `n` scene
    /// descriptions. Used to give Q&A handlers short-term memory without
    /// re-running VLM inference on past frames.
    pub fn recent_context_digest(&self, n: usize) -> Vec<String> {
        if n == 0 || self.results.is_empty() {
            return Vec::new();
        }
        let len = self.results.len();
        let start = len.saturating_sub(n);
        self.results[start..]
            .iter()
            .map(|r| format!("{} {}", r.time, r.text))
            .collect()
    }
}

impl std::fmt::Debug for CameraState {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("CameraState")
            .field("camera_id", &self.camera_id)
            .field("name", &self.name)
            .field("frame_no", &self.frame_no)
            .field("running", &self.running)
            .field("has_cmd_tx", &self.cmd_tx.is_some())
            .finish()
    }
}

/// Shared application state, wrapped in Arc for handler access.
#[derive(Clone)]
pub struct AppState {
    pub config: Config,
    pub cameras: Arc<RwLock<HashMap<String, CameraState>>>,
    pub vlm: Arc<VlmClient>,
    pub asr: Option<Arc<AsrClient>>,
    /// LLM client. Required (config validation enforces non-empty `api_url`).
    pub llm: Arc<LlmClient>,
    pub monitor_profiles: Arc<HashMap<String, MonitorProfile>>,
    /// Broadcast channel for SSE / live UI updates.
    pub events_tx: broadcast::Sender<String>,
    /// Channel for alert events (fired by AlertTracker → consumed by Telegram notifier).
    pub alert_tx: mpsc::UnboundedSender<AlertEvent>,
    pub alert_tracker: Arc<Mutex<AlertTracker>>,
    pub notifier: Option<Arc<TelegramNotifier>>,
    /// Recent periodic summaries (newest last). Capped at `MAX_SUMMARIES`.
    pub summaries: Arc<RwLock<VecDeque<SummaryEntry>>>,
    /// Cache-busting token for static assets — derived from process start
    /// time. Templates append `?v={static_version}` to script/style URLs so
    /// browsers always pick up the latest JS/CSS after a server restart.
    pub static_version: String,
}

impl AppState {
    pub fn new(config: Config) -> (Self, mpsc::UnboundedReceiver<AlertEvent>) {
        let vlm = Arc::new(VlmClient::new(&config.vlm));
        let asr = AsrClient::new(&config.asr).map(Arc::new);
        let llm = Arc::new(LlmClient::new(&config.llm));
        let (events_tx, _) = broadcast::channel(256);
        let (alert_tx, alert_rx) = mpsc::unbounded_channel();
        // Load profiles from external TOML files; fall back to built-in defaults
        let profiles_dir = std::path::Path::new("profiles");
        let monitor_profiles = Arc::new(crate::monitor::load_profiles(profiles_dir));
        let alert_tracker = Arc::new(Mutex::new(AlertTracker::new(&config.monitor)));
        let notifier = TelegramNotifier::from_config(&config.telegram).map(Arc::new);

        let state = Self {
            config,
            cameras: Arc::new(RwLock::new(HashMap::new())),
            vlm,
            asr,
            llm,
            monitor_profiles,
            events_tx,
            alert_tx,
            alert_tracker,
            notifier,
            summaries: Arc::new(RwLock::new(VecDeque::with_capacity(MAX_SUMMARIES))),
            static_version: chrono::Local::now().format("%Y%m%d%H%M%S").to_string(),
        };
        (state, alert_rx)
    }
}

/// Push a summary into the rolling buffer, trimming to `MAX_SUMMARIES` entries.
pub async fn push_summary(state: &AppState, entry: SummaryEntry) {
    let mut buf = state.summaries.write().await;
    buf.push_back(entry);
    while buf.len() > MAX_SUMMARIES {
        buf.pop_front();
    }
}

/// Persist a summary, broadcast it to SSE subscribers, and (only if a
/// Telegram notifier is configured) push it to Telegram.
///
/// **Telegram is optional.** Persistence and SSE broadcast happen
/// unconditionally so the dashboard always receives summaries when the
/// scheduler runs, regardless of `[telegram]` config.
pub async fn record_summary(state: &AppState, entry: SummaryEntry) {
    push_summary(state, entry.clone()).await;

    let event_json = serde_json::to_string(&SseEvent::Summary(entry.clone())).unwrap_or_default();
    let _ = state.events_tx.send(event_json);

    if let Some(ref n) = state.notifier {
        let msg = format!(
            "🕒 *{} min activity summary*\n\n{}",
            entry.window_min, entry.text
        );
        n.send(&msg).await;
    }
}
